### ISSUE TITLE
`compile` function unbinds primitives in repl.

### ISSUE THREAD

**Issue by LeifAndersen** [plt/racket#1036]
Perhaps this is hopeless, but in the slight chance it is not, I will report it anyway.

When you call `compile` at the top level, if the code you compile binds a primitive at the top level then it becomes unbound in the normal repl interaction.

An example of this is:

```
Welcome to Racket v6.2.900.14.
-> +
#<procedure:+>
-> (compile #'(define + 5))
#~
6.2.900.14T�'y�insp0'$?+,P�''
-> +
; +: undefined;
;  cannot reference undefined identifier
; [,bt for context]
```

**Comment by mflatt** [comment]
I'm not happy with this behavior, but I haven't yet figured out how to rebalance evrything. I'm still trying.

**Comment by LeifAndersen** [comment]
Thank you.
