### ISSUE TITLE
string-contains

### ISSUE THREAD

**Issue by eu90h** [plt/racket#1056]
Inspired by [this discussion](https://www.reddit.com/r/Racket/comments/3kaugo/checking_if_a_sentence_is_part_of_another_sentence/), I was curious about adding a `string-contains` procedure to the racket base library.

An implementation of `string-contains` exists already in SRFI-13, but its easy to miss this. Maybe this function could be re-provided out in the base lib? Or maybe a note about SRFI-13 on the [string docs](http://docs.racket-lang.org/reference/strings.html) page?

**Comment by bennn** [comment]
+1

Also, it seems to me that an implementation of `string-contains?` using for loops will be nearly 10x faster than using a regular expression. Argument [here](https://gist.github.com/bennn/0772b7d59bfdb421c048).

**Comment by soegaard** [comment]
Hi Benjamin,

Can you time the following?

(define subs (make-weak-hash))

(define (string-contains4 str sub)
  (match (hash-ref subs sub #f)
    [#f  (define re (regexp sub))
         (hash-set! subs sub re)
         (regexp-match? re str)]
    [re  (regexp-match? re str)]))


/Jens Axel


2015-09-13 10:04 GMT+02:00 Benjamin Greenman <notifications@github.com>:

> +1
>
> Also, it seems to me that an implementation of string-contains? using for
> loops will be nearly 10x faster than using a regular expression. Argument
> here <https://gist.github.com/bennn/0772b7d59bfdb421c048>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plt/racket/issues/1056#issuecomment-139849989>.
>



-- 
-- 
Jens Axel Søgaard

**Comment by bennn** [comment]
4018.87 ms

Here's another example that tests one pair of strings repeatedly. The regular expressions are still a little slower.
```
(define (repeat-test)
  (define s1 "mississippi")
  (define s2 "wishing")
  (for ([f (in-list (list string-contains1 string-contains2 string-contains3 string-contains4))])
    (printf "Testing '~a'\n" (object-name f))
    (benchmark (for ([i (in-range 10000)]) (f s1 s2)))))
```

Results
```
Testing 'string-contains1'
Average of 30 runs: 4.87 ms
Testing 'string-contains2'
Average of 30 runs: 0.87 ms
Testing 'string-contains3'
Average of 30 runs: 0.8 ms
Testing 'string-contains4'
Average of 30 runs: 1.67 ms
```

**Comment by eu90h** [comment]
I'm not well-studied in this, but wouldn't an algorithm like [Boyer-Moore](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore_string_search_algorithm) be faster than regexes?

**Comment by stamourv** [comment]
Added, thanks!
@bennn, could you close this. I can't.

**Comment by bennn** [comment]
@stamouv I can't close it either.

**Comment by stamourv** [comment]
@bennn: Oh right, you didn't open this one. Nevermind.

**Comment by eu90h** [comment]
Thanks @bennn & @stamourv for adding this

**Comment by bennn** [comment]
@eu90h thanks for suggesting
