### ISSUE TITLE
Websocket support is out of date

### ISSUE THREAD

**Issue by hsalokor** [plt/racket#380]
It seems that websocket module currently supports only HyBi 00 specification, which has been phased out by browsers due to security concerns.

This renders the current implementation unsuitable for real world use, since all new browsers only support the newer HyBi 10 specification.

See [this document](http://updates.html5rocks.com/2011/08/What-s-different-in-the-new-WebSocket-protocol) for detailed breakdown of changes.

It seems that [current internal version for the protocol is 13](http://tools.ietf.org/html/rfc6455). Based on quick reading the changes between the HyBi 10 and the latest are minor - the largest breaking change seems to be the new key handshake.

**Comment by lexi-lambda** [comment]
This is an old bug, but let me give an update: this is “fixed” in the sense that Racket no longer ships out of date WebSocket support because it’s been outright removed from the core. The rfc6455 package implements an up-to-date version of the protocol. This issue should likely be closed, but it might be worth looking into pulling that implementation back into the core to replace the removed version.

**Comment by jeapostrophe** [comment]
I think it is very good to thin out the core packages so we can just get what is needed per installation.

**Comment by samth** [comment]
I think there are good arguments on both sides here. Shipping a small standard library reduces installation size, and allows people to choose what they need and experiment with different versions of the library.

On the other hand, choosing something for the standard library makes it easy for people to agree on a "standard" version of the package to coordinate community effort, and makes it easier for new people to learn how to use web sockets in Racket.

**Comment by jbclements** [comment]
> On Jul 21, 2015, at 10:40 AM, Sam Tobin-Hochstadt <notifications@github.com> wrote:
> 
> I think there are good arguments on both sides here. Shipping a small standard library reduces installation size, and allows people to choose what they need and experiment with different versions of the library.
> 
> On the other hand, choosing something for the standard library makes it easy for people to agree on a "standard" version of the package to coordinate community effort, and makes it easier for new people to learn how to use web sockets in Racket.

FWIW, both DuckDuckGo and Google find

http://pkg-build.racket-lang.org/doc/rfc6455/index.html

… as the second hit for racket websockets, which looks pretty good to me.

John
