### ISSUE TITLE
The documentation for `count` from `racket/list` is inaccurate

### ISSUE THREAD

**Issue by lexi-lambda** [plt/racket#866]
The documentation for [`count`](http://docs.racket-lang.org/reference/pairs.html#%28def._%28%28lib._racket%2Flist..rkt%29._count%29%29) states the following:

> Returns `(length (filter proc lst ...))`, but without building the intermediate list.

This isn't quite accurate, because unlike `map`, `filter` does not accept multiple list arguments. Instead, `count` is much closer to something like this:

```
(foldl (lambda (lst ... result) (if (proc lst ...) (add1 result) result))
       0 lst ...)
```

**Comment by bluerider** [comment]
Does count accept multiple lists?

**Comment by bluerider** [comment]
Well, I've just been shown on the IRC that it can accept multiple lists. filter should be replaced with filter-map then.

**Comment by bluerider** [comment]
Fixed up to use filter-map instead of filter:
https://github.com/plt/racket/pull/927

**Comment by samth** [comment]
Fixed.
