### ISSUE TITLE
Inheritance of parent structs is not clear on fields in documentation

### ISSUE THREAD

**Issue by bluerider** [plt/racket#919]
It is not noted in the documentation that inheriting fields from a parent struct requires calling them by the parent struct's name. Example:
(struct parent (test-field))
(struct child parent (dummy-field))

(child-test-field child) is unknown
(parent-test-field child) is known

**Comment by zenspider** [comment]
http://docs.racket-lang.org/guide/define-struct.html#%28part._struct-subtypes%29

makes it pretty clear, but that example, or equivalent, should probably be added to the reference for completeness.

**Comment by bluerider** [comment]
I agree now that I look at it more closely. However, I think it should be mentioned explicitly that class methods are inherited verbatim.

**Comment by zenspider** [comment]
> On Apr 21, 2015, at 23:57, bluerider <notifications@github.com> wrote:
> 
> I agree now that I look at it more closely. However, I think it should be mentioned explicitly that class methods are inherited verbatim.

agreed

**Comment by bluerider** [comment]
Submitted Pull Request #925

**Comment by bluerider** [comment]
Fixed in c44cffe5a88c1221697cffe23dacaec42e976c4d
