### ISSUE TITLE
spurious DrRacket dialog error 

### ISSUE THREAD

**Issue by mbutterick** [plt/racket#937]
Perhaps it's just me, but after I rebuilt from git today (commit 542b960d128f771899c2fbc9b6b70bc9594dac75), DrRacket keeps popping a "DrRacket Internal Error" dialog with this message:

> info.rkt: no info for scribblings
  context...:
   /Users/mb/git/racket/pkgs/racket-index/setup/xref.rkt:29:3: for-loop
   /Users/mb/git/racket/pkgs/racket-index/setup/xref.rkt:23:0: get-dests
   /Users/mb/git/racket/pkgs/racket-index/setup/xref.rkt:19:0: get-rendered-doc-directories
   /Users/mb/git/racket/racket/share/pkgs/drracket/drracket/private/syncheck/blueboxes-gui.rkt:671:2: fetch
   /Users/mb/git/racket/racket/share/pkgs/drracket/drracket/private/syncheck/blueboxes-gui.rkt:670:0: get-blueboxes-cache
   /Users/mb/git/racket/racket/share/pkgs/drracket/drracket/private/syncheck/blueboxes-gui.rkt:444:4: compute-tag+rng method in ...ck/blueboxes-gui.rkt:173:2
   /Users/mb/git/racket/racket/share/pkgs/gui-lib/framework/private/coroutine.rkt:47:20
   /Users/mb/git/racket/racket/share/pkgs/gui-lib/framework/private/coroutine.rkt:56:0: coroutine-run
   /Users/mb/git/racket/racket/collects/racket/contract/private/arrow-val-first.rkt:265:18
   /Users/mb/git/racket/racket/share/pkgs/drracket/drracket/private/syncheck/blueboxes-gui.rkt:410:4: update-the-strs method in ...ck/blueboxes-gui.rkt:173:2
   /Users/mb/git/racket/racket/share/pkgs/gui-lib/framework/private/logging-timer.rkt:41:0: log-timeline/proc
   /Users/mb/git/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/timer.rkt:34:38
   /Users/mb/git/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6
   /Users/mb/git/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:505:32
   /Users/mb/git/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:653:3

**Comment by rfindler** [comment]
This is a bug somewhere, but probably you can avoid the bad code path by running "raco setup" with no arguments (and letting it fully complete).

**Comment by rfindler** [comment]
I believe I fixed this with this commit: https://github.com/plt/racket/commit/a9ac3be43c8ba2ca83c9409a3e3f4847b2c599c6

**Comment by mbutterick** [comment]
There might be more to this. I’ve been trying to rebuild from source today and I get hangs repeatedly at `raco setup: 3 making: <pkgs>/drracket/drracket/private/syncheck`.

**Comment by mbutterick** [comment]
FWIW, I rolled back to commit 39fda5ec9eac8bd17d276cc35e28c55ed66e9e64 and was able to build successfully.

**Comment by rfindler** [comment]
That symptom doesn't seem especially related to the stacktrace or commit that I pushed, but it's hard to tell.

I don't suppose that if you run `raco make -v *` in the corresponding directory (and then hit control-c when it gets stuck) you get any more informative output?

**Comment by mbutterick** [comment]
I’ll try that if I come across the error again.
