### ISSUE TITLE
Itermittent desecriptive error report from serve/servlet

### ISSUE THREAD

**Issue by siddharthist** [plt/racket#947]
I have found that when using `serve/servlet`, with kwarg `#:port 80`, while I sometimes get the informative 
```
tcp-listen: listen failed
  port number: 80
  system error: Permission denied; errno=13
  context...:
   run-server
There was an error starting the Web server
```
I also sometimes just get 
```
There was an error starting the Web server
```
They occur about half of the time each. 

The expected behavior is that running the same code twice produces the same error report, and preferrably the more descriptive one.

**Comment by jeapostrophe** [comment]
This error message is coming from the operating system. If you look up the error number, 13, you'll see that the text for it is "Permission Denied". http://www.virtsync.com/c-error-codes-include-errno

Almost certainly this means that you are not running as root (and thus don't have permission to bind that port) or possibly that another process has already bound it and you can't take it over.

You'll have to talk to your OS provider about a more exact message :(
