### ISSUE TITLE
Unable to find a reader source

### ISSUE THREAD

**Issue by Gozala** [plt/racket#951]
I spend about > 30 mins trying to find the actual source of the reader, by which I mean code that takes string / file and returns syntax form. Can someone please point it out ? I think it would also make sense to put a pointer to it in documentation somewhere.

**Comment by samth** [comment]
The code is here: https://github.com/plt/racket/blob/master/racket/src/racket/src/read.c

I'm not sure how linking to that in the documentation would be explanatory, though.

**Comment by Gozala** [comment]
@samth thanks for the pointer, I assumed reader was implemented in racket itself which is probably why I struggled with finding it.

> I'm not sure how linking to that in the documentation would be explanatory, though.

I guess I just really wished for some sort of intro how parser / compiler pipeline is set up and where relevant code lives.

Thanks
