### ISSUE TITLE
racket/match appears to evaluate ?-based predicates many times on the same inputs

### ISSUE THREAD

**Issue by rfindler** [plt/racket#952]
The printouts you get from running this code show that the `L4e?` predicate is being called many many times on the same inputs, presumably because the predicates in the `?` patterns can be called many times. This makes this function take exponential time.

I'm not sure if this is avoidable, but I have a vague memory of this coming up before and I don't see anything in the documentation about it.

The code below prints out a stream of numbers -- those numbers are the number of times that the same argument is supplied to `L4e?` and they get quite large. (4,379,424 is the maximum, I believe.)

```
#lang racket/base
(require racket/match
         racket/list)

(define ht (make-hash))
(define (L4e? e-exp)
  (hash-set! ht e-exp (+ (hash-ref ht e-exp 0) 1))
  (printf "~a\n" (hash-ref ht e-exp 0))
  (match e-exp
    [`(,(? is-biop?) ,(? L4e?) ,(? L4e?)) #t]
    [`(,_ ,(? L4e?)) #t]
    [`(new-array ,(? L4e?) ,(? L4e?)) #t]
    [`(new-tuple ,(? L4e?) ...) #t]
    [`(aref ,(? L4e?) ,(? L4e?)) #t]
    [`(aset ,(? L4e?) ,(? L4e?) ,(? L4e?)) #t]
    [`(alen ,(? L4e?)) #t]
    [`(print ,(? L4e?)) #t]
    [`(make-closure ,(? symbol?) ,(? L4e?)) #t]
    [`(closure-proc ,(? L4e?)) #t]
    [`(begin ,(? L4e?) ,(? L4e?)) #t]
    [`(closure-vars ,(? L4e?)) #t]
    [`(let ((,(? symbol?) ,(? L4e?))) ,(? L4e?)) #t]
    [`(if ,(? L4e?) ,(? L4e?) ,(? L4e?)) #t]
    [`(,(? L4e?) ...) #t]
    [(? L3v?) #t]
    [_ #f]))

(define (is-biop? sym) (or (is-aop? sym) (is-cmp? sym)))
(define (is-aop? sym) (memq sym '(+ - *)))
(define (is-cmp? sym) (memq sym '(< <= =)))
(define (L3v? v) (or (number? v) (symbol? v)))

(printf "starting\n")
(time      
 (L4e? '(let ((less_than (make-closure :lambda_0 (new-tuple))))
          (let ((L5_swap (make-closure :lambda_1 (new-tuple))))
            (let ((L5_sort_helper (new-tuple 0)))
              (begin
                (aset L5_sort_helper 0 (make-closure :lambda_2 (new-tuple L5_sort_helper L5_swap)))
                (let ((L5_sort (new-tuple 0)))
                  (begin
                    (aset L5_sort 0 (make-closure :lambda_3 (new-tuple L5_sort_helper L5_sort)))
                    (print (let ((f (aref L5_sort 0)))
                             ((closure-proc f)
                              (closure-vars f)
                              (new-tuple 3 1 9 4 5 6 2 8 7 10)
                              less_than)))))))))))
```

**Comment by jeapostrophe** [comment]
This happened to me once before. My ? fund had effects that were repeating.
Sam said don't do it and that it has to do with the reordering and
duplication in the match row algorithm.

Jay

On Tuesday, June 2, 2015, Robby Findler <notifications@github.com> wrote:

> The printouts you get from running this code show that the L4e? predicate
> is being called many many times on the same inputs, presumably because the
> predicates in the ? patterns can be called many times. This makes this
> function take exponential time.
>
> I'm not sure if this is avoidable, but I have a vague memory of this
> coming up before and I don't see anything in the documentation about it.
>
> The code below prints out a stream of numbers -- those numbers are the
> number of times that the same argument is supplied to L4e? and they get
> quite large. (4,379,424 is the maximum, I believe.)
>
> #lang racket/base
> (require racket/match
>          racket/list)
>
> (define ht (make-hash))
> (define (L4e? e-exp)
>   (hash-set! ht e-exp (+ (hash-ref ht e-exp 0) 1))
>   (printf "~a\n" (hash-ref ht e-exp 0))
>   (match e-exp
>     [`(,(? is-biop?) ,(? L4e?) ,(? L4e?)) #t]
>     [`(,_ ,(? L4e?)) #t]
>     [`(new-array ,(? L4e?) ,(? L4e?)) #t]
>     [`(new-tuple ,(? L4e?) ...) #t]
>     [`(aref ,(? L4e?) ,(? L4e?)) #t]
>     [`(aset ,(? L4e?) ,(? L4e?) ,(? L4e?)) #t]
>     [`(alen ,(? L4e?)) #t]
>     [`(print ,(? L4e?)) #t]
>     [`(make-closure ,(? symbol?) ,(? L4e?)) #t]
>     [`(closure-proc ,(? L4e?)) #t]
>     [`(begin ,(? L4e?) ,(? L4e?)) #t]
>     [`(closure-vars ,(? L4e?)) #t]
>     [`(let ((,(? symbol?) ,(? L4e?))) ,(? L4e?)) #t]
>     [`(if ,(? L4e?) ,(? L4e?) ,(? L4e?)) #t]
>     [`(,(? L4e?) ...) #t]
>     [(? L3v?) #t]
>     [_ #f]))
>
> (define (is-biop? sym) (or (is-aop? sym) (is-cmp? sym)))
> (define (is-aop? sym) (memq sym '(+ - *)))
> (define (is-cmp? sym) (memq sym '(< <= =)))
> (define (L3v? v) (or (number? v) (symbol? v)))
>
> (printf "starting\n")
> (time
>  (L4e? '(let ((less_than (make-closure :lambda_0 (new-tuple))))
>           (let ((L5_swap (make-closure :lambda_1 (new-tuple))))
>             (let ((L5_sort_helper (new-tuple 0)))
>               (begin
>                 (aset L5_sort_helper 0 (make-closure :lambda_2 (new-tuple L5_sort_helper L5_swap)))
>                 (let ((L5_sort (new-tuple 0)))
>                   (begin
>                     (aset L5_sort 0 (make-closure :lambda_3 (new-tuple L5_sort_helper L5_sort)))
>                     (print (let ((f (aref L5_sort 0)))
>                              ((closure-proc f)
>                               (closure-vars f)
>                               (new-tuple 3 1 9 4 5 6 2 8 7 10)
>                               less_than)))))))))))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plt/racket/issues/952>.
>


-- 
Jay McCarthy
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by rfindler** [comment]
On Tue, Jun 2, 2015 at 11:23 AM, Jay McCarthy <notifications@github.com>
wrote:

> This happened to me once before. My ? fund had effects that were repeating.
> Sam said don't do it and that it has to do with the reordering and
> duplication in the match row algorithm.
>

Yeah, that makes sense to me.

So I"ll wait for "official confirmation" and then suggest that we explain
this super clearly in the docs so hopefully others don't run into this
pitfall.

Robby

**Comment by jeapostrophe** [comment]
The documentation of 'match' says this at the bottom: "Note that the
matching process may destructure the input multiple times, and may
evaluate expressions embedded in patterns such as (app expr pat) in
arbitrary order, or multiple times. Therefore, such expressions must
be safe to call multiple times, or in an order other than they appear
in the original program."

Jay

On Tue, Jun 2, 2015 at 12:25 PM, Robby Findler <notifications@github.com> wrote:
> On Tue, Jun 2, 2015 at 11:23 AM, Jay McCarthy <notifications@github.com>
> wrote:
>
>> This happened to me once before. My ? fund had effects that were
>> repeating.
>> Sam said don't do it and that it has to do with the reordering and
>> duplication in the match row algorithm.
>>
>
> Yeah, that makes sense to me.
>
> So I"ll wait for "official confirmation" and then suggest that we explain
> this super clearly in the docs so hopefully others don't run into this
> pitfall.
>
> Robby
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Jay McCarthy
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by rfindler** [comment]
Oh, I missed that.

I'd suggest something next to the specific ? case that has an example that
demonstrates bad behavior, tho.

This is an example that doesn't demonstrate the problem and I don't get why.

```
#lang racket

(define (bt? x)
  (printf ">> ~s\n" x)
  (match x
    [(cons (? bt?) (? bt?)) #t]
    [_ (number? x)]))

 (bt? (cons (cons (cons 1 2)
                  (cons 3 4))
            (cons (cons 5 6)
                  (cons 7 8))))

```

**Comment by samth** [comment]
That program doesn't use `(? bt?)` in multiple match clauses.

However, I think I can fix `match` to call the function many fewer times in @rfindler's example. Working on that now.
