### ISSUE TITLE
Nested `begin-for-syntax` forms cause a segmentation fault

### ISSUE THREAD

**Issue by lexi-lambda** [plt/racket#975]
On a snapshot, for whatever reason, it seems like nesting `begin-for-syntax` forms causes a segmentation fault (perhaps a bug related to switching to the new expander)?

```sh
$ racket --version
Welcome to Racket v6.2.900.4.
$ cat fail.rkt
#lang racket
(begin-for-syntax
  (begin-for-syntax))
$ racket fail.rkt
fish: Job 1, 'racket fail.rkt ' terminated by signal SIGSEGV (Address boundary error)
```

I tested this on 801a8950bb9a7c4bb218637ce135db04d1e7de7a and 9fe6c138cf0e145349824f8d9ca5ce524de85a5b.

**Comment by mflatt** [comment]
I've pushed a repair. Thanks for the report!
