### ISSUE TITLE
Build failed on Visual studio 2015

### ISSUE THREAD

**Issue by rexdf** [plt/racket#996]
It can easily be built on win8.1 visual studio 2013 for itself and all `raco pkg install -i main-distribution`. when upgrading to win10, I installed vs2015 and not vs2013.

after patching to:
-  `racket/src/worksp/*/*.vcxproj`

add `<PlatformToolset>v100</PlatformToolset>` to all exist `<PropertyGroup ... </PropertyGroup>`

-  `racket/src/worksp/genvsx.c`

```c
#if _MSC_VER >= 1900
  /* VS 2015 */
  vers = "140";
#elif _MSC_VER >= 1800
```

it can be build on Visual Studio 2015. But I can not fix the the following error. Any suggestion?

```bash
A:\src\racket\racket\src\worksp\gc2>..\..\..\racketcgc -G ..\..\..\etc -cu make.rkt
error.c
Error [CALL] 204 in ../../racket/src/error.c: Bad place for function call, starting tok is __acrt_iob_func.
xform: Errors converting
  context...:
   A:\src\racket\racket\src\worksp\gc2\xform-collects\compiler\private\xform.rkt:8:2: xform
   A:\src\racket\racket\src\worksp\gc2\xform-collects\xform\xform-mod.rkt: [running body]
   A:\src\racket\racket\src\racket\gc2\xform.rkt: [running body]
   A:\src\racket\racket\src\worksp\gc2\make.rkt:117:8
error xforming
  context...:
   A:\src\racket\racket\src\worksp\gc2\make.rkt:96:0: try
   A:\src\racket\racket\collects\racket\private\map.rkt:53:19: loop
   A:\src\racket\racket\src\worksp\gc2\make.rkt: [running body]

A:\src\racket\racket\src\worksp\gc2>if errorlevel 1 exit /B 1
```

**Comment by mflatt** [comment]
Adding `__acrt_iob_func` to the `non-functions` list in "racket/collects/compiler/private/xform.rkt" may let you make progress. You might have to delete a copy of "collects" in "racket/src/worksp/gc2/xform-collects".
